name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Lua and Luarocks
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.1 luarocks

      - name: Install Test Framework (Busted)
        run: luarocks install --only-deps pipeflow-0.1.0-1.rockspec --local

      - name: Run Tests
        run: /home/runner/.luarocks/bin/busted --verbose
